version: "3.8"

services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate-ms-zh
    ports:
      - "5001:5000"
    volumes:
      - lt-ms-zh-models:/home/libretranslate/.local
    command: >
      --load-only "en,ms,zh"
      --host "*"
    restart: unless-stopped
    networks:
      - e-kamus-network

networks:
  e-kamus-network:
    driver: bridge

volumes:
  lt-ms-zh-models: